- clean: ["~"]

- defaults:
      link:
          create: true
          force: true
          relink: true

- link:
      ~/.zsh_aliases: ./lib/shell/zsh/.zsh_aliases
      ~/.zsh_env:     ./lib/shell/zsh/.zsh_env
      ~/.zsh_functions: ./lib/shell/zsh/.zsh_functions
      ~/.zsh_extra:     ./lib/shell/zsh/.zsh_extra
      ~/.zshrc:      ./lib/shell/zsh/.zshrc

- link:
      ~/.gitconfig: ./lib/shell/git/.gitconfig

- link:
      ~/.vim/autoload/plug.vim: ./packages/vim-plug/plug.vim
      ~/.tmux.conf: ./lib/shell/prompt/.tmux.conf
      ~/.vimrc: ./lib/shell/prompt/.vimrc
      ~/.config/starship.toml: ./lib/shell/prompt/starship.toml

- link:
      ~/.ssh/config: ./lib/shell/ssh/config
      ~/.ssh/known_hosts: ./lib/shell/ssh/known_hosts

- shell:
      - description: Configure package manager
        command: bash --login lib/core/config.sh
        stdin: true
        stdout: true
        stderr: true
      - description: Configure OS
        command: bash --login lib/os/config.sh
        stdin: true
        stdout: true
        stderr: true
      - description: Configure shell
        command: bash --login lib/shell/config.sh
        stdin: true
        stdout: true
        stderr: true
