tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/core"
tap "homebrew/services"

brew "bash"
brew "starship"

cask "arc"
cask "font-fira-code-nerd-font"
cask "font-fira-mono-nerd-font"
cask "visual-studio-code"
