brew "dockutil"
brew "cocoapods"

cask "android-studio", greedy: true
cask "intellij-idea", greedy: true
cask "pycharm", greedy: true
cask "mpv", greedy: true
cask "google-chrome", greedy: true
cask "docker", greedy: true
cask "flutter", greedy: true
cask "font-fira-code-nerd-font", greedy: true
cask "kitty", greedy: true
cask "raycast", greedy: true
cask "visual-studio-code", greedy: true

mas "XCode", id: 497799835
